version: '2'
services:
  docker-portainer:
    image: 'portainer/portainer'
    ports:
      - '9000:9000'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always 
    labels:
      opstack.prog.name: 'opstack-portainer'
  jenkins-master:
    image: 'jenkins/master:2.32.3'
    user: root
    ports:
        - '8080:8080'
        - '50000:50000'
    volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - JAVA_OPTS='-Dhudson.model.ParametersAction.keepUndefinedParameters=true'
    restart: always 
    labels:
      opstack.prog.name: 'opstack-jenkins'
