#!/bin/bash

for i in /etc/profile.d/*.sh ; do
  if [ -r "$i" ]; then
    if [ "${-#*i}" != "$-" ]; then
      . "$i"
    else
      . "$i" > /dev/null
    fi
  fi
done


if [ $# -eq 1 ]; then
	# if `docker run` only has one arguments, we assume user is running alternate command like `bash` to inspect the image
	exec "$@"
else

  LABELS="${LABELS:-docker}"
  EXECUTORS="${EXECUTORS:-1}"
  FSROOT="${FSROOT:-${JENKINS_AGENT_HOME}}"

  # jenkins swarm slave
  JAR=`ls -1 /usr/share/jenkins/swarm-client-*.jar | tail -n 1`
  echo ${LABELS} > /tmp/swarmLabels

  # use docker secret import -master -password -username
  echo Running java $JAVA_OPTS -jar $JAR -fsroot $HOME $PARAMS "$@"
  exec java $JAVA_OPTS -jar $JAR -fsroot $FSROOT -labelsFile /tmp/swarmLabels -executors=$EXECUTORS -name=docker-${HOSTNAME} $(cat /run/secrets/jenkins)
fi

